### PR TITLE
optionally allow empty input on decode, fixes #33

### LINKED ISSUE #33: Option to allow empty bodies
Many existing formatters (like `ring-middleware-format`) allow empty bodies, just reads them as `nil`. Use case for this is a client, which always sets the `content-type` header but conditionally sets the body. Currently, Muuntaja fails on these requests (as `nil` is invalid in the JSON & Transit specs).

=> new option `[:http :allow-empty-body?]`

### PR DESCRIPTION
**Pull request by ikitommi**
is the option name good? Should be something more explicit?

* `:allow-empty-input?`
* `:allow-empty-body-on-decode?`
* `:allow-nil-on-decode?`

### CODE REVIEW

File: src/clj/muuntaja/core.clj [hunk 1]
```diff
@@ -68,12 +69,22 @@
...
+                ;; duct-style generator
+                (if (vector? $)
+                  (let [[f opts] $]
+                    (f (merge opts spec-opts)))
+                  $)
+
+                ;; optional guard on empty imput
+                (if (and allow-empty-input? decode?)
+                  (fn [^InputStream is charset]
+                    (if (pos? (.available is)) ($ is charset)))
```
Comment (ikitommi) [inline src/clj/muuntaja/core.clj]: InputStream javadocs say that:

> A subclass' implementation of this method may choose to throw an
>    * {@link IOException} if this input stream has been closed by
>     * invoking the {@link #close()} method.

I guess we don't have to think about this?

**Comment by ikitommi** [comment]
the guard-function is optionally generated at creation time, so there is **zero** performance penalty it this in not used. Cool.
